const data = [
  {
    id: 1,
    title: "Notbuk Apple MacBook Pro 13 MNEP3RU/A Silver",
    img: "apple2.jpg",
    price: 3500,
    properties: {
      Model: "MNEP3RU/A",
      Screen: 13,
      Videocard: "Apple M2",
      Prosessor: "Apple M2",
      SSD: "256 GB",
      Nucleus: 8,
      color: "Silver",
      Producer: "Apple",
    },
  },
  {
    id: 2,
    title: "Notbuk HP Pavilion Aero 13-BE0020UR (5R2Z9EA)",
    img: "hp2.jpg",
    price: 1900,
    properties: {
      Model: "13-BE0020UR",
      Screen: 13.3,
      Videocard: "YOX",
      Prosessor: "Ryzen 5",
      SSD: "512 GB",
      Nucleus: 4,
      color: "Silver",
      Producer: "HP",
    },
  },
  {
    id: 3,
    title: "Notbuk HUAWEI MateBook D 16 Space Gray (53013JHP)",
    img: "huawei.jpg",
    price: 2070,
    properties: {
      Model: "53013JHP",
      Screen: 16,
      Videocard: "Intel Iris Xe Graphics",
      Prosessor: "Core i5",
      SSD: "512 GB",
      Nucleus: 6,
      color: "Space Grey",
      Producer: "HUAWEI",
    },
  },
  {
    id: 4,
    title: "Notbuk Asus VivoBook S15 OLED M3205QA-MA117 (90NB0XX2-M00510)",
    img: "asus.jpg",
    price: 1900,
    properties: {
      Model: "M3205QA-MA117",
      Screen: 15.6,
      Videocard: "AMD Radeon Graphics",
      Prosessor: "Ryzen 5",
      SSD: "256 GB",
      Nucleus: 6,
      color: "Indie Black",
      Producer: "Asus",
    },
  },
  {
    id: 5,
    title: "Noutbuk Acer Aspire 3 A315-35-C95V (NX.A6LER.00H)",
    img: "acer.jpg",
    price: 750,
    properties: {
      Model: "A315-35-C95V",
      Screen: 15.6,
      Videocard: "Daxili Intel",
      Prosessor: "Celeron",
      SSD: "256 GB",
      Nucleus: 2,
      color: "Pure Silver",
      Producer: "Acer",
    },
  },
  {
    id: 6,
    title: "Notbuk Asus TUF Dash F15 2022 FX517Z-AS73 (90NR09Q3-M004E0)",
    img: "asus2.jpg",
    price: 3330,
    properties: {
      Model: "TUF Dash F15 2022 FX517Z-AS73",
      Screen: 15.6,
      Videocard: "GeForce RTX 3060",
      Prosessor: "Core i7",
      SSD: "512 GB",
      Nucleus: 2,
      color: "Black",
      Producer: "Asus",
    },
  },
  {
    id: 7,
    title: "Notbuk HP Pavilion 14-DV0023UR (4C9W6EA)",
    img: "hp.jpg",
    price: 1400,
    properties: {
      Model: "14-DV0023UR",
      Screen: 14,
      Videocard: "Intel UHD Graphics",
      Prosessor: "Core i3",
      SSD: "256 GB",
      Nucleus: 2,
      color: "White",
      Producer: "HP",
    },
  },
  {
    id: 8,
    title: "Notbuk Lenovo IdeaPad 3 15ITL6 (82H801R1RK)",
    img: "lenovo.jpg",
    price: 2000,
    properties: {
      Model: "IdeaPad 3 15ITL6",
      Screen: 15.6,
      Videocard: "GeForce MX450",
      Prosessor: "Core i7",
      SSD: "256 GB",
      Nucleus: 4,
      color: "Silver",
      Producer: "Lenovo",
    },
  },
  {
    id: 9,
    title: "Notbuk Dell Vostro 3510 P112F (3510273851879)",
    img: "dell.jpg",
    price: 1800,
    properties: {
      Model: "Vostro 3510 P112F",
      Screen: 15.6,
      Videocard: "Intel UHD Graphics",
      Prosessor: "Core i5",
      SSD: "512 GB",
      Nucleus: 4,
      color: "Carbon Black",
      Producer: "Dell",
    },
  },
  {
    id: 10,
    title: "Notbuk Lenovo IdeaPad Gaming 3 15IHU6 (82K100H3RK)",
    img: "lenovo2.jpg",
    price: 1650,
    properties: {
      Model: "IdeaPad Gaming 3 15IHU6",
      Screen: 15.6,
      Videocard: "GeForce RTX 3050 TI",
      Prosessor: "Core i7",
      SSD: "512 GB",
      Nucleus: 4,
      color: "Black",
      Producer: "Lenovo",
    },
  },
  {
    id: 11,
    title: "Notbuk Apple MacBook Pro 16 MNWD3RU/A Silver",
    img: "apple.jpg",
    price: 6530,
    properties: {
      Model: "MacBook Pro 16",
      Screen: 16.2,
      Videocard: "M2 Pro",
      Prosessor: "Apple M2 Pro",
      SSD: "1 TB",
      Nucleus: 12,
      color: "Silver",
      Producer: "Apple",
    },
  },
  {
    id: 12,
    title: "Notbuk Acer Aspire A515-44G-R2JQ (NX.HW2ER.005)",
    img: "acer2.jpg",
    price: 1330,
    properties: {
      Model: "A515-44G-R2JQ",
      Screen: 15.6,
      Videocard: "Daxili Intel",
      Prosessor: "Celeron",
      SSD: "256 GB",
      Nucleus: 4,
      Color: "Space Grey",
      Producer: "Acer",
    },
  },
];

export default data
